on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start docker
        id: hello  
        uses: Chandolkar001/test_github_actions@fccc814828bce57150e99ab8e346b605fb6c4ec3
        with:
          who-to-greet: 'Shreyas'

        
