on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start docker
        id: hello  
        uses: Chandolkar001/test_github_actions@b11a5099dae305231ba9328835b8290c69e1d083
        with:
          who-to-greet: 'Shreyas'
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
        
