on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout file
        uses: actions/checkout@v3
      - name: main scan
        uses: Chandolkar001/test_github_actions@da9428971cf3171ebcc38fb877de6cc306d4354b
        with:
          who-to-greet: 'secret-scan'
          github-context : ${{ toJson(github.event) }}
          auth-token: ${{ secrets.AUTH_TOKEN }}
          api-endpoint: ${{ secrets.API_ENDPOINT }}


        
