on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout file
        uses: actions/checkout@v3
      - name: Start docker action
        id: hello  
        uses: Chandolkar001/test_github_actions@b1c6ddabe0529203890f065b28ab7b27ab3eb52b

        
