on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout file
        uses: actions/checkout@v3
      - name: Start docker 
        env:
          test_secret: ${{ secrets.TEST_SECRET }}
        id: hello  
        uses: Chandolkar001/test_github_actions@f627322aad5d886b3b3b304e2f97038cb3be4709
        with:
          who-to-greet: 'vulnerability-scan'


        
