on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout file
        uses: actions/checkout@v3
      - name: main 
        uses: Chandolkar001/test_github_actions@17435f3bbd6a432507fa8ae1812780c7535b977e
        with:
          who-to-greet: 'all'
          github-context : ${{ toJson(github.event) }}
          auth-token: ${{ secrets.AUTH_TOKEN }}
          api-endpoint: ${{ secrets.API_ENDPOINT }}


        
