on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout file
        uses: actions/checkout@v3
      # - name: Dump GitHub context
      #   env:
      #     GITHUB_CONTEXT: ${{ toJSON(github.event) }}
      #   run: echo "$GITHUB_CONTEXT"
      - name: Start docker 
        env:
          test_secret: ${{ secrets.TEST_SECRET }}
          GITHUB_CONTEXT : ${{ toJson(github.event) }}
        id: hello  
        uses: Chandolkar001/test_github_actions@9d385bfe817052b8b18413fc103230606e342ad9
        with:
          who-to-greet: 'vulnerability-scan'
          end-point: ${{ secrets.CDX_API_ENDPOINT }}
          auth: ${{ secrets.CDX_AUTHZ_TOKEN }}
          key: ${{ secrets.SECRET_KEY }}

        
