on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Start docker
        id: hello  
        uses: Chandolkar001/test_github_actions@13a0452a84c128b095ddbdde6d455a208cbc5775
      #   with:
      #     who-to-greet: 'Shreyas'
      # - name: Get the output time
      #   run: echo "The time was ${{ steps.hello.outputs.time }}"
        
