on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout file
        uses: actions/checkout@v3
      - name: Scan
        env:
          CDX_AUTHZ_TOKEN: ${{ secrets.CDX_AUTHZ_TOKEN }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          CDX_API_ENDPOINT: ${{ secrets.CDX_API_ENDPOINT }}
        uses: Chandolkar001/test_github_actions@81ab4e08dc76bd8bf815c05702cbd0b45de04b87
        with:
          who-to-greet: 'multi-scan'
          event: ${{ toJson(github.event) }}


        
