on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout file
        uses: actions/checkout@v3
      - name: Start docker
        id: hello  
        uses: Chandolkar001/test_github_actions@30ee7a03d5680946d5daae74719eda399d6f2827
        with:
          who-to-greet: 'file.txt'

        
