on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout file
        uses: actions/checkout@v3
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Start docker 
        env:
          test_secret: ${{ secrets.TEST_SECRET }}
        id: hello  
        uses: Chandolkar001/test_github_actions@6f6e83b38c85b0415c8e57c5ad0ccbbfa827f401
        with:
          who-to-greet: 'vulnerability-scan'
          end-point: ${{ secrets.CDX_API_ENDPOINT }}
          auth: ${{ secrets.CDX_AUTHZ_TOKEN }}
          key: ${{ secrets.SECRET_KEY }}

        
