on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout file
        uses: actions/checkout@v3
      - name: Scan
        env:
          GITHUB_CONTEXT : ${{ toJson(github.event) }}
          CDX_AUTHZ_TOKEN: ${{ secrets.CDX_AUTHZ_TOKEN }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          CDX_API_ENDPOINT: ${{ secrets.CDX_API_ENDPOINT }}
        uses: Chandolkar001/test_github_actions@f186ddaa096cf72c29898f045d552bc8991d12ad
        with:
          who-to-greet: 'secret-scan'

        
