on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v3
      - name: Start docker
        id: hello  
        uses: Chandolkar001/test_github_actions@d71ab38b18902d60b502f09a63296dc83b0b2dfd
        with:
          who-to-greet: 'Shreyas'
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
        
