on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start docker
        id: hello  
        uses: Chandolkar001/test_github_actions@cb456330e95368ad2230b5acbc32c0c70ac2ef93
      #   with:
      #     who-to-greet: 'Shreyas'
      # - name: Get the output time
      #   run: echo "The time was ${{ steps.hello.outputs.time }}"
        
