on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start docker
        id: hello  
        uses: Chandolkar001/test_github_actions@8c023c215172e165835abc094823c4965e704337
        with:
          who-to-greet: 'Shreyas'
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
        
