on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout file
        uses: actions/checkout@v3
      - name: Start docker action
        id: hello  
        uses: Chandolkar001/test_github_actions@24eb29e9fbe8996d55657a14571c2d69e32bb223
        with:
          who-to-greet: 'app.py'

        
