on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout file
        uses: actions/checkout@v3
      - name: Scan
        env:
        uses: Chandolkar001/test_github_actions@c9ff33c9ac314db6d56a0b3be476dcbbd3ee8acd
        with:
          who-to-greet: 'secret-scan'
          github-context : ${{ toJson(github.event) }}
          auth-token: ${{ secrets.AUTH_TOKEN }}
          api-endpoint: ${{ secrets.API_ENDPOINT }}


        
