on: [push]

jobs:
  hello_job_work:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: Chandolkar001/test_github_actions@006d604a20aeb3a581c070427b20e14772bfb9ca
        with:
          who-to-greet: 'Tron'
