on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout file
        uses: actions/checkout@v3
      - name: check for parent dir
        run: |
          echo "Current directory: $(pwd)"
      - name: Start docker
        id: hello  
        uses: Chandolkar001/test_github_actions@46ae9afe499027de42dee8129f6e179acd8fc8e0
        with:
          who-to-greet: 'app.py'

        
