on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout file
        uses: actions/checkout@v3
      - name: Start docker 
        id: hello  
        uses: Chandolkar001/test_github_actions@97c079157c682f855c60a3ab7d6c90c422cfa9e0
        with:
          who-to-greet: 'vulnerability scan'

        
