on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout file
        uses: actions/checkout@v3
      - name: Start docker image
        id: hello  
        uses: Chandolkar001/test_github_actions@969771b2876780d346b2ca4c85e4951e1a29ca2b
        with:
          who-to-greet: 'file.txt'
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
        
