on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start docker action
        id: hello  
        uses: Chandolkar001/test_github_actions@b16c482ee5d383c49716bfcdb952f0ceea9ea7bd
        with:
          who-to-greet: 'Shreyas'
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
        
