on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout file
        uses: actions/checkout@v3
      - name: Start docker 
        id: hello  
        uses: Chandolkar001/test_github_actions@39c8c709a0091aea3c27b1ab72a8f6f388f2c7ea
        with:
          who-to-greet: 'vulnerability-scan'

        
