on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout file
        uses: actions/checkout@v3
      - name: Start docker
        id: hello  
        uses: Chandolkar001/test_github_actions@4d8159c902861608d5acec6ae97ded9052d33aae
        with:
          who-to-greet: 'file.txt'
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
        
