on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout file
        uses: actions/checkout@v3
      - name: Scan
        uses: Chandolkar001/test_github_actions@3c48992021c235f5151c83d228b0bd8555e0cbde
        with:
          who-to-greet: 'secret-scan'
          github-context : ${{ toJson(github.event) }}
          auth-token: ${{ secrets.AUTH_TOKEN }}
          api-endpoint: ${{ secrets.API_ENDPOINT }}


        
