on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout file
        uses: actions/checkout@v3
      - name: Start docker
        id: hello  
        uses: Chandolkar001/test_github_actions@2a1bf83b8c92209c1488b583e534eca9128e2555
        with:
          who-to-greet: 'app.py'

        
